### ISSUE TITLE
node application not running 

### ISSUE THREAD

**Issue by SyCode7** [BarathArivazhagan/spring-cloud-sidecar-polygot#1]
Hi, i tried to follow your tutorial. Hpwever the node application sfails to run. Here is the error produced:

`
wsstore-node_1          |

wsstore-node_1          | > wsstore-node-express@1.0.0 start /usr/wstore-node-express   C:UsersKennedysidecar_test
wsstore-node_1          | > tsc --watch & nodemon dist/App.js
wsstore-node_1          |
wsstore-node_1          | sh: 1: nodemon: not found
wsstore-node_1          | npm ERR! file sh
wsstore-node_1          | npm ERR! code ELIFECYCLE
wsstore-node_1          | npm ERR! errno ENOENT
wsstore-node_1          | npm ERR! syscall spawn
wsstore-node_1          | npm ERR! wsstore-node-express@1.0.0 start: `tsc --watch & nodemon dist/App.js`
wsstore-node_1          | npm ERR! spawn ENOENT
wsstore-node_1          | npm ERR!
wsstore-node_1          | npm ERR! Failed at the wsstore-node-express@1.0.0 start script.
wsstore-node_1          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
wsstore-node_1          |
wsstore-node_1          | npm ERR! A complete log of this run can be found in:
wsstore-node_1          | npm ERR!     /root/.npm/_logs/2018-06-03T10_43_22_562Z-debug.log
`

**Comment by BarathArivazhagan** [comment]
@SyCode7  Do you have tsc installed ? please provide the tsc version

**Comment by SyCode7** [comment]
you mean typescript ?

**Comment by BarathArivazhagan** [comment]
I am closing this ticket. if you face any issues let me know.
